version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8080}:80
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat_php
